### ISSUE TITLE
Error in RC_CallRecordings_Download.phar

### ISSUE THREAD

**Issue by FCSdevelopers** [anilkumarbp/RingCentral-Call-Generator-Recordings-Downloader#1]
Trying to install PHAR file using command “PHP RC_CallRecordings_Download.phar” and it gives error on line 62. Error image attached.

![ringcentral_error](https://cloud.githubusercontent.com/assets/10531515/13785548/034445ce-eafa-11e5-94c1-f24023f5003c.png)

**Comment by anilkumarbp** [comment]
the php version that you are on. needs the curl support enabled.

**Comment by anilkumarbp** [comment]
http://stackoverflow.com/questions/2939820/how-to-enable-curl-installed-ubuntu-lamp-stack

**Comment by bdeanindy** [comment]
http://askubuntu.com/questions/9293/how-do-i-install-curl-in-php5

There are many tutorials available online, as well as manuals in PHP, which can guide you in configuring your server.

Once you have that resolved, please try installing using Composer, and if you continue to experience issues provide the error messages for continued support.

**Comment by FCSdevelopers** [comment]
Hi Anil,

I have installed curl supported php and  composer on my Linux and then I start following steps given on github. I run command “composer install” this command install all the things and not give any error all installation done.

Then I run “php create-phar.php” and got an error. This error solved by adding “phar.readonly = off” in php.ini.

Next command php create-phar.php run and create RC_CallRecording_Download.phar.
When I run command php RC_CallRecording_Download.phar giving error. Error screen print given.

Please let me know what I have to do for solve this error.

Giving you the screen print which show php –ini, curl version and error detail.

Thanks and regards,

Ravindra Joshi

**Comment by FCSdevelopers** [comment]
I have installed curl supported php and  composer on my Linux and then I start following steps given on github. I run command “composer install” this command install all the things and not give any error all installation done.  

Then I run “php create-phar.php” and got an error. This error solved by adding “phar.readonly = off” in php.ini. 

Next command php create-phar.php run and create RC_CallRecording_Download.phar.
When I run command php RC_CallRecording_Download.phar giving error. Error screen print given.

Please let me know what I have to do for solve this error.

Giving you the screen print which show php –ini, curl version and error detail.
![solved_error_screen](https://cloud.githubusercontent.com/assets/10531515/13852397/d729d050-ec87-11e5-9854-d5469ec7b9bd.png)
![php and curl installed](https://cloud.githubusercontent.com/assets/10531515/13852421/f5b9d682-ec87-11e5-992b-4b5924258c08.png)
![error_screen_1](https://cloud.githubusercontent.com/assets/10531515/13852423/fcfa51d8-ec87-11e5-87bb-8bb2c1c3e6d4.png)

**Comment by anilkumarbp** [comment]
Did you input the app credentilas into the config.json ?

**Comment by FCSdevelopers** [comment]
yes

**Comment by FCSdevelopers** [comment]
Config.json created and all required details added in that. I try to run index.php also but this is giving error. I have remove some script as we just want S3 so other code related to drobox and other removed. Then also getting error.

Please check the code which I use for index.php and error screen print attached.
index.php
 **<?php
use RingCentral\SDK\Http\HttpException;
use RingCentral\http\Response;
use RingCentral\SDK;

require('vendor/autoload.php');

// check if a config.ini file exists
$config = "";
$skipCallLog = "";
$skipRingOut = "";
$skipDownloadS3 = "";
$skipDownload = "";

$filename = './config.json';

// $skipCallLog =

if (file_exists($filename)) {
        $config = json_decode(file_get_contents($filename), true);
        $skipCallLog = $config['skipCallLog'];
        $skipRingOut = $config['skipRingOut'];
        $skipDownload = $config['skipDownload'];
        $skipDownloadS3 = $config['skipDownloadS3'];
        $skipDownloadDropbox = $config['skipDownloadDropbox'];
        // To authenticate
        require(**DIR** . '/demo/authData.php');
        // Recordings-Download-S3
        if ($skipDownloadS3!="True" || $skipDownloadS3=="") {
                print "Test 4: callRecording_S3.php\n";
                print "Downloading Recordings to S3\n";
            require(**DIR** . '/demo/callRecording_S3.php');
        } else {
                print "Test 4: callRecording_S3.php - skipping...\n";
        }
}
else {

```
    print "Kindly include a config.json in the folder\n";
```

}
// require(**DIR** . '/demo/call_log.php');
// require(**DIR** . '/demo/ringout.php');
// require(**DIR** . '/demo/callRecording.php');
// require(**DIR** . '/demo/callRecording_S3.php');
// require(**DIR** . '/demo/callRecording_Dropbox.**php');

---

Next I try to run direct callRecording_S3.php from demo folder and this also give me error. Error screen print attached.

I try to find out from where error create and I found when I run index.php the error create from authData.php while refresh the token on this line “$platform->refresh();”.

When I run callRecording_S3.php this create error while authenticate AWS access.

I have check config.json detail for appKey, appSecret, server, username, password for Ring Central and  amazonAccessKey, amazonSecretKey for AWS are correct.

![error_index](https://cloud.githubusercontent.com/assets/10531515/13878792/aa246bc6-ed39-11e5-813b-619a59cf0a4d.png)
![error_callrecording_s3](https://cloud.githubusercontent.com/assets/10531515/13878801/b55110bc-ed39-11e5-8eda-2a345c173f0c.png)

**Comment by anilkumarbp** [comment]
Closing the issue as resolved. 

Resolution: Move over to a new release "0.1.2" to accommodate .env instead of config.json.
