### ISSUE TITLE
Suppress SSL verification in RingCentral PHP SDK

### ISSUE THREAD

**Issue by LingForCC** [anilkumarbp/RingCentral-Call-Generator-Recordings-Downloader#4]
In order to make the demo work, I need to add following code in `ringcentral-php/src/Http/Client.php`

`curl_setopt($ch,CURLOPT_SSL_VERIFYPEER, false);`

before sending any request to server.

Of course, this is not a good solution in production environment when considering from security perspective. My understanding is that we may need to add CA info in the production environment before deploying the app.

**Comment by anilkumarbp** [comment]
Right now, there is no SSL verification process adopted in the code. But I see the point perhaps, we should implement SSL verification with the Production Environment. 

All the environment and account details would be part of the .env file.
