### ISSUE TITLE
Provide documentation for "Announcement-Only-Extension"

### ISSUE THREAD

**Issue by grokify** [anilkumarbp/RingCentral-Call-Generator-Recordings-Downloader#8]
The `README.md` indicates configuring an "Announcement-Only-Extension". Please provide a link to the instructions on how to do this, for example:
- [KB 4492 - http://success.ringcentral.com/articles/RC_Knowledge_Article/4492](http://success.ringcentral.com/articles/RC_Knowledge_Article/4492)

**Comment by anilkumarbp** [comment]
Added the link to the README.md
